# Generated by Django 5.2.8 on 2025-11-14 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Dataset name", max_length=255)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("DEM", "Digital Elevation Model"),
                            ("SHAPEFILE", "Shapefile"),
                            ("TIMESERIES", "Time Series (CSV/Excel)"),
                            ("HMS", "HEC-HMS Output"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_checksum",
                    models.CharField(
                        blank=True, help_text="SHA256 checksum", max_length=64
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Validation"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("ERROR", "Validation Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("validation_message", models.TextField(blank=True)),
                (
                    "crs",
                    models.CharField(
                        blank=True,
                        help_text="Coordinate Reference System (EPSG code)",
                        max_length=50,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "db_table": "datasets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RasterLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField(help_text="Raster width in pixels")),
                ("height", models.IntegerField(help_text="Raster height in pixels")),
                ("bands", models.IntegerField(default=1, help_text="Number of bands")),
                ("bounds_minx", models.FloatField(help_text="Minimum X coordinate")),
                ("bounds_miny", models.FloatField(help_text="Minimum Y coordinate")),
                ("bounds_maxx", models.FloatField(help_text="Maximum X coordinate")),
                ("bounds_maxy", models.FloatField(help_text="Maximum Y coordinate")),
                (
                    "pixel_size_x",
                    models.FloatField(help_text="Pixel size in X direction"),
                ),
                (
                    "pixel_size_y",
                    models.FloatField(help_text="Pixel size in Y direction"),
                ),
                ("nodata_value", models.FloatField(blank=True, null=True)),
                (
                    "min_value",
                    models.FloatField(
                        blank=True, help_text="Minimum elevation", null=True
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True, help_text="Maximum elevation", null=True
                    ),
                ),
                (
                    "mean_value",
                    models.FloatField(
                        blank=True, help_text="Mean elevation", null=True
                    ),
                ),
                (
                    "std_value",
                    models.FloatField(
                        blank=True, help_text="Standard deviation", null=True
                    ),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raster_metadata",
                        to="hydropower.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raster Layer",
                "verbose_name_plural": "Raster Layers",
                "db_table": "raster_layers",
            },
        ),
        migrations.CreateModel(
            name="VectorLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("POINT", "Point"),
                            ("LINESTRING", "LineString"),
                            ("POLYGON", "Polygon"),
                            ("MULTIPOINT", "MultiPoint"),
                            ("MULTILINESTRING", "MultiLineString"),
                            ("MULTIPOLYGON", "MultiPolygon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feature_count", models.IntegerField(help_text="Number of features")),
                ("bounds_minx", models.FloatField(help_text="Minimum X coordinate")),
                ("bounds_miny", models.FloatField(help_text="Minimum Y coordinate")),
                ("bounds_maxx", models.FloatField(help_text="Maximum X coordinate")),
                ("bounds_maxy", models.FloatField(help_text="Maximum Y coordinate")),
                (
                    "attributes",
                    models.JSONField(default=dict, help_text="Field names and types"),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_metadata",
                        to="hydropower.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Layer",
                "verbose_name_plural": "Vector Layers",
                "db_table": "vector_layers",
            },
        ),
        migrations.CreateModel(
            name="TimeSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("RAINFALL", "Rainfall"),
                            ("DISCHARGE", "Discharge"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "station_id",
                    models.CharField(
                        blank=True, help_text="Station or source ID", max_length=100
                    ),
                ),
                ("datetime", models.DateTimeField(help_text="Observation datetime")),
                ("value", models.FloatField(help_text="Measured value")),
                (
                    "units",
                    models.CharField(
                        blank=True, help_text="Units (m³/s, mm, etc.)", max_length=50
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries",
                        to="hydropower.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Series",
                "verbose_name_plural": "Time Series",
                "db_table": "timeseries",
                "ordering": ["datetime"],
                "indexes": [
                    models.Index(
                        fields=["dataset", "datetime"],
                        name="timeseries_dataset_eebd7e_idx",
                    ),
                    models.Index(
                        fields=["station_id", "datetime"],
                        name="timeseries_station_14c7db_idx",
                    ),
                ],
            },
        ),
    ]
