# Generated by Django 5.2.8 on 2025-11-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterlayer",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="DEM preview image",
                null=True,
                upload_to="thumbnails/%Y/%m/%d/",
            ),
        ),
    ]
