# Generated by Django 5.2.8 on 2025-11-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0002_rasterlayer_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorlayer",
            name="has_invalid_geometries",
            field=models.BooleanField(
                default=False, help_text="Whether shapefile contains invalid geometries"
            ),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="invalid_geometry_count",
            field=models.IntegerField(
                default=0, help_text="Number of invalid/null geometries"
            ),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Shapefile preview image",
                null=True,
                upload_to="thumbnails/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="vectorlayer",
            name="geometry_type",
            field=models.CharField(
                choices=[
                    ("POINT", "Point"),
                    ("LINESTRING", "LineString"),
                    ("POLYGON", "Polygon"),
                    ("MULTIPOINT", "MultiPoint"),
                    ("MULTILINESTRING", "MultiLineString"),
                    ("MULTIPOLYGON", "MultiPolygon"),
                    ("GEOMETRYCOLLECTION", "GeometryCollection"),
                ],
                max_length=20,
            ),
        ),
    ]
