# Generated by Django 5.2.8 on 2025-11-14 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0003_vectorlayer_has_invalid_geometries_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMSRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        help_text="Storm event name or simulation scenario",
                        max_length=200,
                    ),
                ),
                (
                    "return_period",
                    models.CharField(
                        blank=True,
                        help_text="Return period (e.g., '25-year', '100-year')",
                        max_length=50,
                    ),
                ),
                (
                    "num_elements",
                    models.IntegerField(
                        default=0,
                        help_text="Number of HMS elements (subbasins, junctions, etc.)",
                    ),
                ),
                (
                    "num_timesteps",
                    models.IntegerField(
                        default=0, help_text="Number of timesteps in simulation"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="Simulation start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Simulation end time", null=True
                    ),
                ),
                (
                    "peak_discharge",
                    models.FloatField(
                        blank=True,
                        help_text="Peak discharge across all elements (m³/s)",
                        null=True,
                    ),
                ),
                (
                    "peak_element",
                    models.CharField(
                        blank=True,
                        help_text="Element ID with peak discharge",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hms_runs",
                        to="hydropower.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "HEC-HMS Run",
                "verbose_name_plural": "HEC-HMS Runs",
                "db_table": "hms_runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
