# Generated by Django 5.2.8 on 2025-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0004_hmsrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterlayer",
            name="filled_dem_path",
            field=models.CharField(
                blank=True, help_text="Path to filled/breached DEM", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="flow_accumulation_path",
            field=models.CharField(
                blank=True, help_text="Path to flow accumulation raster", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="flow_direction_path",
            field=models.CharField(
                blank=True, help_text="Path to D8 flow direction raster", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="is_preprocessed",
            field=models.BooleanField(
                default=False, help_text="Whether DEM has been preprocessed"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="preprocessing_date",
            field=models.DateTimeField(
                blank=True, help_text="When preprocessing was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="preprocessing_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FILLED", "Depression Filling"),
                    ("BREACHED", "Depression Breaching"),
                ],
                help_text="Method used for depression removal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="preprocessing_params",
            field=models.JSONField(
                blank=True, default=dict, help_text="Parameters used for preprocessing"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="preprocessing_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Statistics from preprocessing outputs",
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="smoothed_dem_path",
            field=models.CharField(
                blank=True,
                help_text="Path to smoothed DEM (if applied)",
                max_length=500,
            ),
        ),
    ]
