# Generated by Django 5.2.8 on 2025-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0005_rasterlayer_filled_dem_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterlayer",
            name="stream_count",
            field=models.IntegerField(
                default=0, help_text="Number of stream segments extracted"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="stream_threshold",
            field=models.IntegerField(
                blank=True,
                help_text="Flow accumulation threshold used for streams",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="watershed_count",
            field=models.IntegerField(
                default=0, help_text="Number of watersheds delineated"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="watershed_delineated",
            field=models.BooleanField(
                default=False,
                help_text="Whether watershed delineation has been performed",
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="watershed_delineation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When watershed delineation was completed",
                null=True,
            ),
        ),
    ]
