# Generated by Django 5.2.8 on 2025-11-16 14:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0006_rasterlayer_stream_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        help_text="Stream segment LineString (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "length_m",
                    models.FloatField(help_text="Stream segment length in meters"),
                ),
                (
                    "stream_order",
                    models.IntegerField(
                        default=1, help_text="Strahler or Shreve stream order"
                    ),
                ),
                (
                    "stream_threshold",
                    models.IntegerField(
                        help_text="Flow accumulation threshold used for extraction"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for stream extraction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="hydropower.rasterlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Network",
                "verbose_name_plural": "Stream Networks",
                "db_table": "stream_network",
                "ordering": ["-stream_order", "-length_m"],
                "indexes": [
                    models.Index(
                        fields=["raster_layer", "stream_order"],
                        name="stream_netw_raster__a71291_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatershedPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watershed_id",
                    models.IntegerField(help_text="Watershed identifier from raster"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Watershed boundary polygon (UTM Zone 51N)",
                        srid=32651,
                    ),
                ),
                (
                    "area_m2",
                    models.FloatField(help_text="Watershed area in square meters"),
                ),
                (
                    "area_km2",
                    models.FloatField(help_text="Watershed area in square kilometers"),
                ),
                (
                    "perimeter_m",
                    models.FloatField(help_text="Watershed perimeter in meters"),
                ),
                (
                    "stream_length_m",
                    models.FloatField(
                        default=0, help_text="Total stream length within watershed (m)"
                    ),
                ),
                (
                    "stream_length_km",
                    models.FloatField(
                        default=0, help_text="Total stream length within watershed (km)"
                    ),
                ),
                (
                    "drainage_density",
                    models.FloatField(
                        default=0, help_text="Stream length per unit area (km/km²)"
                    ),
                ),
                (
                    "stream_count",
                    models.IntegerField(
                        default=0, help_text="Number of stream segments in watershed"
                    ),
                ),
                (
                    "compactness",
                    models.FloatField(
                        default=0, help_text="Gravelius compactness coefficient"
                    ),
                ),
                (
                    "stream_threshold",
                    models.IntegerField(
                        help_text="Flow accumulation threshold used for stream extraction"
                    ),
                ),
                (
                    "delineated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for delineation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watersheds",
                        to="hydropower.rasterlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watershed Polygon",
                "verbose_name_plural": "Watershed Polygons",
                "db_table": "watershed_polygons",
                "ordering": ["-area_km2"],
                "indexes": [
                    models.Index(
                        fields=["raster_layer", "watershed_id"],
                        name="watershed_p_raster__2d8e86_idx",
                    ),
                    models.Index(
                        fields=["area_km2"], name="watershed_p_area_km_9b7553_idx"
                    ),
                ],
            },
        ),
    ]
