# Generated by Django 5.2.8 on 2025-11-16 14:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0007_streamnetwork_watershedpolygon"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.IntegerField(
                        help_text="Unique node identifier within stream network"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Node location (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("source", "Source (headwater)"),
                            ("confluence", "Confluence (junction)"),
                            ("outlet", "Outlet (terminal)"),
                            ("junction", "Junction"),
                            ("divergence", "Divergence"),
                        ],
                        help_text="Type of stream node",
                        max_length=20,
                    ),
                ),
                (
                    "incoming_streams",
                    models.IntegerField(
                        default=0, help_text="Number of incoming stream segments"
                    ),
                ),
                (
                    "outgoing_streams",
                    models.IntegerField(
                        default=0, help_text="Number of outgoing stream segments"
                    ),
                ),
                (
                    "stream_threshold",
                    models.IntegerField(
                        help_text="Flow accumulation threshold used for extraction"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Stream Node",
                "verbose_name_plural": "Stream Nodes",
                "db_table": "stream_nodes",
                "ordering": ["node_id"],
            },
        ),
        migrations.AddField(
            model_name="streamnetwork",
            name="from_node",
            field=models.IntegerField(default=0, help_text="Upstream node ID"),
        ),
        migrations.AddField(
            model_name="streamnetwork",
            name="is_confluence",
            field=models.BooleanField(
                default=False, help_text="Stream ends at confluence"
            ),
        ),
        migrations.AddField(
            model_name="streamnetwork",
            name="is_outlet",
            field=models.BooleanField(
                default=False, help_text="Stream is an outlet (terminal)"
            ),
        ),
        migrations.AddField(
            model_name="streamnetwork",
            name="to_node",
            field=models.IntegerField(default=0, help_text="Downstream node ID"),
        ),
        migrations.AddField(
            model_name="streamnetwork",
            name="upstream_count",
            field=models.IntegerField(
                default=0, help_text="Number of upstream tributaries"
            ),
        ),
        migrations.AddIndex(
            model_name="streamnetwork",
            index=models.Index(
                fields=["from_node", "to_node"], name="stream_netw_from_no_17b863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamnetwork",
            index=models.Index(
                fields=["stream_order", "is_outlet"],
                name="stream_netw_stream__6968e7_idx",
            ),
        ),
        migrations.AddField(
            model_name="streamnode",
            name="raster_layer",
            field=models.ForeignKey(
                help_text="Source DEM used for stream extraction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stream_nodes",
                to="hydropower.rasterlayer",
            ),
        ),
        migrations.AddIndex(
            model_name="streamnode",
            index=models.Index(
                fields=["raster_layer", "node_type"],
                name="stream_node_raster__33976c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="streamnode",
            index=models.Index(
                fields=["node_id"], name="stream_node_node_id_543a2f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamnode",
            unique_together={("raster_layer", "node_id")},
        ),
    ]
