# Generated by Django 5.2.8 on 2025-11-16 14:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0008_streamnode_streamnetwork_from_node_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_id",
                    models.CharField(
                        help_text="Unique site identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[("INLET", "Inlet"), ("OUTLET", "Outlet")],
                        help_text="Inlet or Outlet",
                        max_length=10,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Site location (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        help_text="Elevation at site (meters above sea level)"
                    ),
                ),
                (
                    "stream_order",
                    models.IntegerField(
                        blank=True, help_text="Strahler stream order at site", null=True
                    ),
                ),
                (
                    "distance_to_stream",
                    models.FloatField(
                        default=0.0, help_text="Distance to nearest stream (meters)"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for elevation extraction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_points",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "stream_network",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated stream segment (if on stream network)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_points",
                        to="hydropower.streamnetwork",
                    ),
                ),
                (
                    "stream_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated stream node (if at confluence/outlet)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_points",
                        to="hydropower.streamnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Point",
                "verbose_name_plural": "Site Points",
                "db_table": "site_points",
                "ordering": ["site_id"],
            },
        ),
        migrations.CreateModel(
            name="SitePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pair_id",
                    models.CharField(
                        help_text="Unique pair identifier (inlet_id-outlet_id)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        help_text="Line connecting inlet to outlet (UTM Zone 51N)",
                        srid=32651,
                    ),
                ),
                (
                    "river_distance",
                    models.FloatField(
                        help_text="Distance along river between inlet and outlet (meters)"
                    ),
                ),
                (
                    "euclidean_distance",
                    models.FloatField(
                        help_text="Straight-line distance between inlet and outlet (meters)"
                    ),
                ),
                (
                    "head",
                    models.FloatField(
                        help_text="Hydraulic head: H = z_inlet - z_outlet (meters)"
                    ),
                ),
                (
                    "discharge",
                    models.FloatField(
                        blank=True, help_text="Design discharge Q (m³/s)", null=True
                    ),
                ),
                (
                    "efficiency",
                    models.FloatField(
                        default=0.7, help_text="Turbine efficiency factor η (0.6–0.85)"
                    ),
                ),
                (
                    "power",
                    models.FloatField(
                        blank=True,
                        help_text="Power output P = ρ × g × Q × H × η (kW)",
                        null=True,
                    ),
                ),
                (
                    "hms_element_id",
                    models.CharField(
                        blank=True,
                        help_text="HEC-HMS element ID (junction/reach)",
                        max_length=100,
                    ),
                ),
                (
                    "discharge_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of discharge value", null=True
                    ),
                ),
                (
                    "discharge_type",
                    models.CharField(
                        blank=True,
                        help_text="Discharge type (peak/average/etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "return_period",
                    models.CharField(
                        blank=True,
                        help_text="Return period or scenario (e.g., 100-year)",
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Multi-criteria score for site ranking",
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Rank among all site pairs (1=best)",
                        null=True,
                    ),
                ),
                (
                    "meets_head_constraint",
                    models.BooleanField(
                        default=True, help_text="Passes minimum head constraint"
                    ),
                ),
                (
                    "meets_distance_constraint",
                    models.BooleanField(
                        default=True,
                        help_text="Passes minimum river distance constraint",
                    ),
                ),
                (
                    "meets_land_constraint",
                    models.BooleanField(
                        default=True, help_text="Passes land proximity constraint"
                    ),
                ),
                (
                    "is_feasible",
                    models.BooleanField(
                        default=True, help_text="Passes all constraints"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hms_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated HEC-HMS simulation (discharge source)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_pairs",
                        to="hydropower.hmsrun",
                    ),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for calculations",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_pairs",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "inlet",
                    models.ForeignKey(
                        help_text="Upstream inlet point",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_inlet",
                        to="hydropower.sitepoint",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        help_text="Downstream outlet point",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_outlet",
                        to="hydropower.sitepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Pair",
                "verbose_name_plural": "Site Pairs",
                "db_table": "site_pairs",
                "ordering": ["-power", "-head"],
            },
        ),
        migrations.AddIndex(
            model_name="sitepoint",
            index=models.Index(
                fields=["raster_layer", "site_type"],
                name="site_points_raster__2c44ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitepoint",
            index=models.Index(
                fields=["site_type", "elevation"], name="site_points_site_ty_517f63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitepoint",
            index=models.Index(
                fields=["stream_order"], name="site_points_stream__79c1f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitepair",
            index=models.Index(
                fields=["raster_layer", "is_feasible"],
                name="site_pairs_raster__c43fa5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitepair",
            index=models.Index(
                fields=["power", "head"], name="site_pairs_power_243811_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitepair",
            index=models.Index(
                fields=["is_feasible", "-power"], name="site_pairs_is_feas_a0abf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitepair",
            index=models.Index(fields=["rank"], name="site_pairs_rank_f6c555_idx"),
        ),
    ]
