# Generated by Django 5.2.8 on 2025-11-16 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0009_sitepoint_sitepair_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="Unique job identifier (UUID or custom)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("DEM_PREPROCESSING", "DEM Preprocessing"),
                            ("WATERSHED_DELINEATION", "Watershed Delineation"),
                            ("STREAM_EXTRACTION", "Stream Network Extraction"),
                            ("SITE_PAIRING", "Inlet-Outlet Site Pairing"),
                            ("DISCHARGE_ASSOCIATION", "Discharge Association"),
                            ("POWER_CALCULATION", "Power Calculation"),
                            ("EXPORT_CSV", "CSV Export"),
                            ("EXPORT_GEOJSON", "GeoJSON Export"),
                            ("EXPORT_PDF", "PDF Export"),
                        ],
                        help_text="Type of processing job",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Processing parameters and configuration (JSON)",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Time job was queued",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Time job started execution", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Time job completed", null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Job execution duration in seconds",
                        null=True,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, help_text="Job progress (0-100%)"),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True, help_text="Current progress message", max_length=500
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full error traceback for debugging"
                    ),
                ),
                (
                    "warning_messages",
                    models.JSONField(
                        blank=True, default=list, help_text="List of warning messages"
                    ),
                ),
                (
                    "results_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of processing results (counts, statistics, etc.)",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for async execution",
                        max_length=100,
                    ),
                ),
                (
                    "input_datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Input datasets used for this processing run",
                        related_name="processing_runs",
                        to="hydropower.dataset",
                    ),
                ),
                (
                    "output_raster_layers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Generated raster layers",
                        related_name="processing_runs",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "output_site_pairs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Generated site pairs",
                        related_name="processing_runs",
                        to="hydropower.sitepair",
                    ),
                ),
                (
                    "output_streams",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Generated stream segments",
                        related_name="processing_runs",
                        to="hydropower.streamnetwork",
                    ),
                ),
                (
                    "output_watersheds",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Generated watershed polygons",
                        related_name="processing_runs",
                        to="hydropower.watershedpolygon",
                    ),
                ),
                (
                    "parent_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent job if this is part of a processing pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_jobs",
                        to="hydropower.processingrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Run",
                "verbose_name_plural": "Processing Runs",
                "db_table": "processing_runs",
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["job_id"], name="processing__job_id_a62b8b_idx"
                    ),
                    models.Index(
                        fields=["status", "-queued_at"],
                        name="processing__status_f52057_idx",
                    ),
                    models.Index(
                        fields=["job_type", "status"],
                        name="processing__job_typ_35c1e3_idx",
                    ),
                    models.Index(
                        fields=["-queued_at"], name="processing__queued__f8972d_idx"
                    ),
                ],
            },
        ),
    ]
