# Generated by Django 5.2.8 on 2025-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0010_processingrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterlayer",
            name="site_pair_count",
            field=models.IntegerField(
                default=0, help_text="Number of site pairs generated"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="site_pairing_completed",
            field=models.BooleanField(
                default=False, help_text="Whether site pairing has been performed"
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="site_pairing_date",
            field=models.DateTimeField(
                blank=True, help_text="When site pairing was completed", null=True
            ),
        ),
    ]
