# Generated by Django 5.2.8 on 2025-11-20 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0011_rasterlayer_site_pair_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepair",
            name="channel_geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True,
                help_text="Water conveyance channel path",
                null=True,
                srid=32651,
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="channel_length",
            field=models.FloatField(
                blank=True, help_text="Channel length in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="forebay_tank_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Forebay tank/surge tank location",
                null=True,
                srid=32651,
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="intake_basin_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Water intake/weir location (at inlet)",
                null=True,
                srid=32651,
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="penstock_diameter",
            field=models.FloatField(
                blank=True, help_text="Penstock diameter in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="penstock_geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True,
                help_text="Penstock pipeline (pressure pipe)",
                null=True,
                srid=32651,
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="penstock_length",
            field=models.FloatField(
                blank=True, help_text="Penstock length in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="powerhouse_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Powerhouse location (turbine & generator)",
                null=True,
                srid=32651,
            ),
        ),
        migrations.AddField(
            model_name="sitepair",
            name="settling_basin_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Settling basin location (near intake)",
                null=True,
                srid=32651,
            ),
        ),
    ]
