# Generated by Django 5.2.8 on 2025-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0012_sitepair_channel_geom_sitepair_channel_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepair",
            name="meets_watershed_constraint",
            field=models.BooleanField(
                default=True,
                help_text="Both inlet and outlet are within watershed boundary",
            ),
        ),
    ]
