# Generated by Django 5.2.8 on 2025-12-02 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0013_add_watershed_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterlayer",
            name="discharge_computation_date",
            field=models.DateTimeField(
                blank=True, help_text="When discharge was computed", null=True
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="discharge_computed",
            field=models.BooleanField(
                default=False,
                help_text="Whether spatially-varying discharge has been computed",
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="discharge_q_outlet",
            field=models.FloatField(
                blank=True,
                help_text="Reference Q at outlet used for discharge calculation (m³/s)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rasterlayer",
            name="discharge_raster_path",
            field=models.CharField(
                blank=True,
                help_text="Path to discharge raster (m³/s per cell)",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="ProcessingLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Layer display name", max_length=200),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("DEM", "Digital Elevation Model"),
                            ("FILLED_DEM", "Filled DEM (Depressions Removed)"),
                            ("FLOW_DIRECTION", "Flow Direction (D8)"),
                            ("FLOW_ACCUMULATION", "Flow Accumulation"),
                            ("STREAM_RASTER", "Stream Raster"),
                            ("STREAM_VECTOR", "Stream Network (Vector)"),
                            ("WATERSHED_RASTER", "Watershed Raster"),
                            ("WATERSHED_VECTOR", "Watershed Boundaries (Vector)"),
                            ("DISCHARGE_RASTER", "Discharge (m³/s)"),
                            ("SLOPE", "Slope (Degrees)"),
                            ("ASPECT", "Aspect"),
                            ("SUBBASIN", "Subbasins"),
                            ("SITE_POINTS", "Site Points (Inlets/Outlets)"),
                            ("SITE_PAIRS", "Site Pairs"),
                            ("INFRASTRUCTURE", "Infrastructure Components"),
                            ("CUSTOM", "Custom Layer"),
                        ],
                        help_text="Type of processing layer",
                        max_length=30,
                    ),
                ),
                (
                    "data_format",
                    models.CharField(
                        choices=[
                            ("RASTER", "Raster (GeoTIFF)"),
                            ("VECTOR", "Vector (GeoJSON/Shapefile)"),
                            ("POINT", "Point Features"),
                            ("LINE", "Line Features"),
                            ("POLYGON", "Polygon Features"),
                        ],
                        default="RASTER",
                        help_text="Data format",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(help_text="Path to layer file", max_length=500),
                ),
                (
                    "style",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Layer style configuration (colors, opacity, etc.)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Layer description"),
                ),
                (
                    "processing_step",
                    models.IntegerField(
                        default=0, help_text="Processing step number (for ordering)"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether layer is visible by default"
                    ),
                ),
                (
                    "is_base_layer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a base/background layer",
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Layer statistics"
                    ),
                ),
                ("bounds_minx", models.FloatField(blank=True, null=True)),
                ("bounds_miny", models.FloatField(blank=True, null=True)),
                ("bounds_maxx", models.FloatField(blank=True, null=True)),
                ("bounds_maxy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM/RasterLayer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_layers",
                        to="hydropower.rasterlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Layer",
                "verbose_name_plural": "Processing Layers",
                "db_table": "processing_layers",
                "ordering": ["raster_layer", "processing_step", "name"],
                "unique_together": {("raster_layer", "layer_type")},
            },
        ),
    ]
