# Generated by Django 5.2.8 on 2025-12-07 03:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0014_add_processing_layers"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiversionZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone_id",
                    models.CharField(
                        help_text="Unique zone identifier (e.g., 'DZ_INLET_001')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Diversion zone polygon(s) (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="Zone centroid", null=True, srid=32651
                    ),
                ),
                (
                    "reference_elevation",
                    models.FloatField(
                        help_text="Reference elevation of inlet point (m)"
                    ),
                ),
                (
                    "elevation_tolerance",
                    models.FloatField(
                        default=2.0, help_text="Elevation tolerance used for search (m)"
                    ),
                ),
                (
                    "min_elevation",
                    models.FloatField(help_text="Minimum elevation within zone (m)"),
                ),
                (
                    "max_elevation",
                    models.FloatField(help_text="Maximum elevation within zone (m)"),
                ),
                (
                    "mean_elevation",
                    models.FloatField(help_text="Mean elevation within zone (m)"),
                ),
                (
                    "search_radius",
                    models.FloatField(
                        default=500.0, help_text="Search radius around inlet point (m)"
                    ),
                ),
                ("area_m2", models.FloatField(help_text="Zone area in square meters")),
                ("area_hectares", models.FloatField(help_text="Zone area in hectares")),
                (
                    "perimeter_m",
                    models.FloatField(help_text="Zone perimeter in meters"),
                ),
                (
                    "pixel_count",
                    models.IntegerField(help_text="Number of DEM pixels in zone"),
                ),
                (
                    "mean_slope",
                    models.FloatField(
                        blank=True,
                        help_text="Mean slope within zone (degrees)",
                        null=True,
                    ),
                ),
                (
                    "max_slope",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum slope within zone (degrees)",
                        null=True,
                    ),
                ),
                (
                    "is_contiguous",
                    models.BooleanField(
                        default=True,
                        help_text="Whether zone is a single contiguous area",
                    ),
                ),
                (
                    "fragment_count",
                    models.IntegerField(
                        default=1, help_text="Number of separate fragments"
                    ),
                ),
                (
                    "largest_fragment_area_m2",
                    models.FloatField(
                        blank=True,
                        help_text="Area of largest contiguous fragment",
                        null=True,
                    ),
                ),
                (
                    "distance_to_stream",
                    models.FloatField(
                        blank=True,
                        help_text="Distance from zone centroid to nearest stream (m)",
                        null=True,
                    ),
                ),
                (
                    "suitability_score",
                    models.FloatField(
                        blank=True,
                        help_text="Suitability score for water diversion (0-100)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True, help_text="Time to compute this zone", null=True
                    ),
                ),
                (
                    "inlet_point",
                    models.ForeignKey(
                        help_text="Inlet point around which the zone was computed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diversion_zones",
                        to="hydropower.sitepoint",
                    ),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for elevation analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diversion_zones",
                        to="hydropower.rasterlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diversion Zone",
                "verbose_name_plural": "Diversion Zones",
                "db_table": "diversion_zones",
                "ordering": ["-area_m2"],
            },
        ),
        migrations.AddField(
            model_name="sitepair",
            name="diversion_zone",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated diversion zone (similar elevation area around inlet)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_pair",
                to="hydropower.diversionzone",
            ),
        ),
        migrations.AddIndex(
            model_name="diversionzone",
            index=models.Index(
                fields=["raster_layer", "inlet_point"],
                name="diversion_z_raster__24f13b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diversionzone",
            index=models.Index(
                fields=["reference_elevation"], name="diversion_z_referen_32a71a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diversionzone",
            index=models.Index(
                fields=["area_m2"], name="diversion_z_area_m2_7132cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diversionzone",
            index=models.Index(
                fields=["suitability_score"], name="diversion_z_suitabi_88ea10_idx"
            ),
        ),
    ]
