# Generated by Django 5.2.8 on 2025-12-07 05:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0015_add_diversion_zone_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiversionPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_type",
                    models.CharField(
                        choices=[
                            ("INTAKE_TO_SETTLING", "Intake to Settling Basin"),
                            ("SETTLING_TO_CHANNEL", "Settling Basin to Channel Start"),
                            ("CHANNEL", "Water Conveyance Channel"),
                            ("CHANNEL_TO_FOREBAY", "Channel End to Forebay"),
                            ("FOREBAY_TO_PENSTOCK", "Forebay to Penstock Start"),
                            ("PENSTOCK", "Penstock Pipeline"),
                            ("PENSTOCK_TO_POWERHOUSE", "Penstock End to Powerhouse"),
                            ("FULL_PATH", "Complete Path (Intake to Powerhouse)"),
                        ],
                        help_text="Type of infrastructure path",
                        max_length=30,
                    ),
                ),
                (
                    "path_order",
                    models.IntegerField(
                        help_text="Order in sequence (1=first segment)"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        help_text="Path geometry (UTM Zone 51N)", srid=32651
                    ),
                ),
                ("length_m", models.FloatField(help_text="Path length in meters")),
                (
                    "elevation_start",
                    models.FloatField(help_text="Elevation at path start (m)"),
                ),
                (
                    "elevation_end",
                    models.FloatField(help_text="Elevation at path end (m)"),
                ),
                (
                    "elevation_change",
                    models.FloatField(help_text="Elevation change along path (m)"),
                ),
                (
                    "slope_percent",
                    models.FloatField(help_text="Average slope (percent)"),
                ),
                (
                    "follows_contour",
                    models.BooleanField(
                        default=False, help_text="Path follows elevation contour"
                    ),
                ),
                (
                    "min_ground_clearance",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum clearance above ground (m)",
                        null=True,
                    ),
                ),
                (
                    "terrain_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Elevation profile along path",
                    ),
                ),
                (
                    "construction_notes",
                    models.TextField(
                        blank=True, help_text="Engineering notes for construction"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "site_pair",
                    models.ForeignKey(
                        help_text="Associated site pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diversion_paths",
                        to="hydropower.sitepair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diversion Path",
                "verbose_name_plural": "Diversion Paths",
                "db_table": "diversion_paths",
                "ordering": ["site_pair", "path_order"],
                "indexes": [
                    models.Index(
                        fields=["site_pair", "path_type"],
                        name="diversion_p_site_pa_80bb56_idx",
                    ),
                    models.Index(
                        fields=["path_order"], name="diversion_p_path_or_3b298e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PairingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Pair Accepted"),
                            ("REJECTED", "Pair Rejected"),
                        ],
                        help_text="Accept or reject",
                        max_length=20,
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(help_text="Why this decision was made"),
                ),
                ("head_value", models.FloatField(help_text="Calculated head (m)")),
                (
                    "head_passes",
                    models.BooleanField(help_text="Meets minimum head constraint"),
                ),
                (
                    "head_threshold",
                    models.FloatField(help_text="Required minimum head (m)"),
                ),
                ("distance_value", models.FloatField(help_text="River distance (m)")),
                (
                    "distance_passes",
                    models.BooleanField(help_text="Meets minimum distance constraint"),
                ),
                (
                    "distance_threshold",
                    models.FloatField(help_text="Required minimum distance (m)"),
                ),
                (
                    "watershed_check",
                    models.BooleanField(help_text="Both points in same watershed"),
                ),
                (
                    "land_access_check",
                    models.BooleanField(help_text="Passes land accessibility check"),
                ),
                (
                    "raw_score",
                    models.FloatField(
                        blank=True,
                        help_text="Raw score before normalization",
                        null=True,
                    ),
                ),
                (
                    "normalized_score",
                    models.FloatField(
                        blank=True, help_text="Normalized score (0-100)", null=True
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(default=dict, help_text="All calculated metrics"),
                ),
                (
                    "evaluation_order",
                    models.IntegerField(
                        help_text="Order in which this pair was evaluated"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "inlet",
                    models.ForeignKey(
                        help_text="Inlet point",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_decisions_as_inlet",
                        to="hydropower.sitepoint",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        help_text="Outlet point",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_decisions_as_outlet",
                        to="hydropower.sitepoint",
                    ),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="DEM being processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_decisions",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "site_pair",
                    models.ForeignKey(
                        blank=True,
                        help_text="Created site pair (if accepted)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_decision",
                        to="hydropower.sitepair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pairing Decision",
                "verbose_name_plural": "Pairing Decisions",
                "db_table": "pairing_decisions",
                "ordering": ["raster_layer", "evaluation_order"],
                "indexes": [
                    models.Index(
                        fields=["raster_layer", "decision"],
                        name="pairing_dec_raster__7f6607_idx",
                    ),
                    models.Index(
                        fields=["evaluation_order"],
                        name="pairing_dec_evaluat_9befe4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Data Upload"),
                            ("VALIDATION", "Data Validation"),
                            ("PREPROCESSING", "DEM Preprocessing"),
                            ("WATERSHED", "Watershed Delineation"),
                            ("STREAM_EXTRACTION", "Stream Extraction"),
                            ("SITE_IDENTIFICATION", "Site Point Identification"),
                            ("SITE_PAIRING", "Inlet-Outlet Pairing"),
                            ("DIVERSION_ZONE", "Diversion Zone Generation"),
                            ("DISCHARGE", "Discharge Association"),
                            ("POWER_CALC", "Power Calculation"),
                            ("RANKING", "Site Ranking"),
                            ("EXPORT", "Data Export"),
                        ],
                        help_text="Processing stage",
                        max_length=30,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        help_text="Log level",
                        max_length=10,
                    ),
                ),
                (
                    "step_number",
                    models.IntegerField(
                        help_text="Sequential step number within stage"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Log entry title", max_length=255),
                ),
                ("message", models.TextField(help_text="Detailed log message")),
                (
                    "input_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Input parameters for this step",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Output data and statistics"
                    ),
                ),
                (
                    "validation_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation metrics and quality checks",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to visualization image",
                        max_length=500,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this step occurred",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="How long this step took", null=True
                    ),
                ),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="DEM being processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "site_pair",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related site pair (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="hydropower.sitepair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Log",
                "verbose_name_plural": "Processing Logs",
                "db_table": "processing_logs",
                "ordering": ["raster_layer", "timestamp", "step_number"],
                "indexes": [
                    models.Index(
                        fields=["raster_layer", "stage"],
                        name="processing__raster__faed68_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="processing__timesta_7e778e_idx"
                    ),
                    models.Index(fields=["level"], name="processing__level_91ff53_idx"),
                ],
            },
        ),
    ]
