# Generated by Django 5.2.8 on 2025-12-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0017_sitepair_avg_slope_sitepoint_chainage"),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepair',
            name='channel_path_geom',
            field=models.TextField(
                null=True,
                blank=True,
                help_text='Channel path geometry as WKT (follows stream network)'
            ),
        ),
    ]
