# Generated by Django 5.2.8 on 2025-12-10 02:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0018_make_channel_path_geom_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeirCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_id",
                    models.CharField(
                        help_text="Unique candidate identifier (e.g., 'WEIR_IN_97_79_001')",
                        max_length=100,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Weir candidate location (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(help_text="DEM elevation at weir candidate (m)"),
                ),
                (
                    "distance_from_inlet",
                    models.FloatField(
                        help_text="Distance from inlet point to weir candidate (m)"
                    ),
                ),
                (
                    "elevation_difference",
                    models.FloatField(
                        help_text="Elevation difference: candidate - inlet (m)"
                    ),
                ),
                ("inlet_elevation", models.FloatField(help_text="Inlet elevation (m)")),
                (
                    "inlet_node_id",
                    models.CharField(help_text="Inlet node ID", max_length=100),
                ),
                (
                    "outlet_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of outlets associated with this inlet",
                    ),
                ),
                (
                    "outlet_node_ids",
                    models.TextField(
                        blank=True, help_text="Comma-separated outlet node IDs"
                    ),
                ),
                (
                    "is_toward_outlet",
                    models.BooleanField(
                        default=True,
                        help_text="Whether candidate is in direction toward outlet(s)",
                    ),
                ),
                (
                    "angle_to_outlet_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Angle from inlet to candidate toward outlet (degrees)",
                        null=True,
                    ),
                ),
                (
                    "pair_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of high-ranked pairs using this inlet",
                    ),
                ),
                (
                    "pair_ids_list",
                    models.TextField(blank=True, help_text="Comma-separated pair IDs"),
                ),
                (
                    "suitability_score",
                    models.FloatField(
                        blank=True,
                        help_text="Suitability score for weir location (0-100)",
                        null=True,
                    ),
                ),
                (
                    "rank_within_inlet",
                    models.IntegerField(
                        blank=True,
                        help_text="Rank among candidates for this inlet (1=best)",
                        null=True,
                    ),
                ),
                (
                    "search_radius",
                    models.FloatField(
                        default=500.0, help_text="Search radius used (m)"
                    ),
                ),
                (
                    "elevation_tolerance",
                    models.FloatField(
                        default=20.0, help_text="Elevation tolerance used (m)"
                    ),
                ),
                (
                    "min_distance",
                    models.FloatField(
                        default=100.0, help_text="Minimum distance from inlet (m)"
                    ),
                ),
                (
                    "cone_angle_deg",
                    models.FloatField(
                        default=90.0, help_text="Directional cone half-angle (degrees)"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Weir Candidate",
                "verbose_name_plural": "Weir Candidates",
                "db_table": "weir_candidates",
                "ordering": ["inlet_point", "rank_within_inlet"],
            },
        ),
        migrations.RemoveField(
            model_name="diversionpath",
            name="site_pair",
        ),
        migrations.RemoveField(
            model_name="pairingdecision",
            name="inlet",
        ),
        migrations.RemoveField(
            model_name="pairingdecision",
            name="outlet",
        ),
        migrations.RemoveField(
            model_name="pairingdecision",
            name="raster_layer",
        ),
        migrations.RemoveField(
            model_name="pairingdecision",
            name="site_pair",
        ),
        migrations.RemoveField(
            model_name="processinglog",
            name="raster_layer",
        ),
        migrations.RemoveField(
            model_name="processinglog",
            name="site_pair",
        ),
        migrations.RemoveIndex(
            model_name="sitepoint",
            name="hydropower_sp_stream_chainage_idx",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="avg_slope",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="avg_slope_percent",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="channel_path_geom",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="inlet_discharge",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="outlet_discharge",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="z_inlet",
        ),
        migrations.RemoveField(
            model_name="sitepair",
            name="z_outlet",
        ),
        migrations.RemoveField(
            model_name="sitepoint",
            name="chainage",
        ),
        migrations.RemoveField(
            model_name="sitepoint",
            name="flow_accumulation",
        ),
        migrations.RemoveField(
            model_name="sitepoint",
            name="nodal_discharge",
        ),
        migrations.RemoveField(
            model_name="sitepoint",
            name="stream_segment_id",
        ),
        migrations.AddField(
            model_name="weircandidate",
            name="inlet_point",
            field=models.ForeignKey(
                help_text="Inlet point around which weir candidates were searched",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weir_candidates",
                to="hydropower.sitepoint",
            ),
        ),
        migrations.AddField(
            model_name="weircandidate",
            name="raster_layer",
            field=models.ForeignKey(
                help_text="Source DEM used for weir search",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weir_candidates",
                to="hydropower.rasterlayer",
            ),
        ),
        migrations.AddField(
            model_name="weircandidate",
            name="site_pairs",
            field=models.ManyToManyField(
                help_text="High-ranked IO pairs that use this inlet",
                related_name="weir_candidates",
                to="hydropower.sitepair",
            ),
        ),
        migrations.DeleteModel(
            name="DiversionPath",
        ),
        migrations.DeleteModel(
            name="PairingDecision",
        ),
        migrations.DeleteModel(
            name="ProcessingLog",
        ),
        migrations.AddIndex(
            model_name="weircandidate",
            index=models.Index(
                fields=["raster_layer", "inlet_point"],
                name="weir_candid_raster__f89fcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weircandidate",
            index=models.Index(
                fields=["inlet_node_id"], name="weir_candid_inlet_n_ad5656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weircandidate",
            index=models.Index(
                fields=["suitability_score"], name="weir_candid_suitabi_28b558_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weircandidate",
            index=models.Index(
                fields=["distance_from_inlet"], name="weir_candid_distanc_c75fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weircandidate",
            index=models.Index(
                fields=["rank_within_inlet"], name="weir_candid_rank_wi_57f7ac_idx"
            ),
        ),
    ]
