# Generated by Django 5.2.8 on 2025-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0019_add_weir_candidate_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamnetwork",
            name="is_main_river",
            field=models.BooleanField(
                default=False,
                help_text="Part of main river stem or major reach (for practical site selection)",
            ),
        ),
        migrations.AddIndex(
            model_name="streamnetwork",
            index=models.Index(
                fields=["is_main_river"], name="stream_netw_is_main_e5af82_idx"
            ),
        ),
    ]
