# Generated by Django 5.2.8 on 2025-12-10 14:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0020_add_is_main_river_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="HPNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Unique HP node identifier (e.g., 'HP_001')",
                        max_length=50,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="HP node location (UTM Zone 51N)", srid=32651
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        help_text="Elevation at node (meters above sea level)"
                    ),
                ),
                (
                    "distance_along_channel",
                    models.FloatField(
                        help_text="Distance along main channel from start (m)"
                    ),
                ),
                ("chainage", models.FloatField(help_text="Chainage marker (km)")),
                (
                    "source_vector_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of source vector layer",
                        max_length=200,
                    ),
                ),
                (
                    "sampling_interval",
                    models.FloatField(
                        default=500.0, help_text="Sampling interval along channel (m)"
                    ),
                ),
                (
                    "can_be_inlet",
                    models.BooleanField(
                        default=True, help_text="Can serve as inlet point"
                    ),
                ),
                (
                    "can_be_outlet",
                    models.BooleanField(
                        default=True, help_text="Can serve as outlet point"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "raster_layer",
                    models.ForeignKey(
                        help_text="Source DEM used for elevation extraction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hp_nodes",
                        to="hydropower.rasterlayer",
                    ),
                ),
                (
                    "source_vector_layer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source vector layer (main channel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp_nodes",
                        to="hydropower.vectorlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "HP Node",
                "verbose_name_plural": "HP Nodes",
                "db_table": "hp_nodes",
                "ordering": ["distance_along_channel"],
                "indexes": [
                    models.Index(
                        fields=["raster_layer", "distance_along_channel"],
                        name="hp_nodes_raster__9b0337_idx",
                    ),
                    models.Index(
                        fields=["elevation"], name="hp_nodes_elevati_8acb1b_idx"
                    ),
                    models.Index(
                        fields=["node_id"], name="hp_nodes_node_id_eaa807_idx"
                    ),
                ],
                "unique_together": {("raster_layer", "node_id")},
            },
        ),
    ]
