# Generated by Django 5.2.8 on 2025-12-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0021_hpnode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hpnode",
            options={
                "ordering": ["watershed", "distance_along_channel"],
                "verbose_name": "HP Node",
                "verbose_name_plural": "HP Nodes",
            },
        ),
        migrations.AddField(
            model_name="hpnode",
            name="distance_to_outlet",
            field=models.FloatField(
                blank=True, help_text="Distance to watershed outlet (m)", null=True
            ),
        ),
        migrations.AddField(
            model_name="hpnode",
            name="stream_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Stream segment this node belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_nodes",
                to="hydropower.streamnetwork",
            ),
        ),
        migrations.AddField(
            model_name="hpnode",
            name="watershed",
            field=models.ForeignKey(
                blank=True,
                help_text="Watershed/subbasin containing this HP node",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hp_nodes",
                to="hydropower.watershedpolygon",
            ),
        ),
        migrations.AlterField(
            model_name="hpnode",
            name="distance_along_channel",
            field=models.FloatField(help_text="Distance along stream from start (m)"),
        ),
        migrations.AddIndex(
            model_name="hpnode",
            index=models.Index(
                fields=["watershed", "distance_along_channel"],
                name="hp_nodes_watersh_ee14a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hpnode",
            index=models.Index(
                fields=["stream_segment"], name="hp_nodes_stream__6645db_idx"
            ),
        ),
    ]
