# Generated by Django 5.2.8 on 2025-12-10 18:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hydropower", "0022_add_watershed_fields_to_hp_nodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watershedpolygon",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                help_text="Watershed boundary (Polygon or MultiPolygon, UTM Zone 51N)",
                srid=32651,
            ),
        ),
    ]
